# Generated by Django 6.0.6 on 2026-08-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
