# Generated by Django 6.0.6 on 2026-08-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options_course_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('embed_url', models.URLField(help_text='Χρησιμοποίησε σύνδεσμο ενσωμάτωσης, π.χ. https://www.youtube.com/embed/VIDEO_ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
