# Generated by Django 6.0.6 on 2026-09-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ενότητα Άσκησης',
                'verbose_name_plural': 'Ενότητες Ασκήσεων',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='exercises/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exercises.exercisecategory')),
            ],
            options={
                'verbose_name': 'Αρχείο Ασκήσεων',
                'verbose_name_plural': 'Αρχεία Ασκήσεων',
                'ordering': ['title'],
            },
        ),
    ]
